"""Format book deals as Telegram-friendly Markdown."""

from datetime import datetime, timezone
from typing import Any


def format_report(books: list[dict[str, Any]], new_count: int, 
                  dropped_count: int) -> str:
    """Format the daily deals report for Telegram."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    
    lines = [
        f"📚 *Kindle SFF Deals — {now}*",
        "",
    ]
    
    if not books:
        lines.append("No new Fantasy or Sci\\-Fi deals found today\\.")
        lines.append("")
        lines.append(f"_📊 Stats: {new_count} new, {dropped_count} price drops today_")
        return "\n".join(lines)
    
    lines.append(f"_{len(books)} deals found_ | 🆕 {new_count} new | 📉 {dropped_count} price drops")
    lines.append("")
    
    for i, book in enumerate(books, 1):
        price_str = f"${book['price']:.2f}" if book.get("price") is not None else "N/A"
        title = book.get("title", "Unknown Title")
        author = book.get("author", "")
        url = book.get("url", "")
        
        # Build savings info: "was $19.99, 90% off"
        savings = ""
        list_price = book.get("list_price")
        savings_pct = book.get("savings_pct")
        if list_price and savings_pct:
            savings = f" ~~was ${list_price:.2f}~~ \\({savings_pct}% off\\)"
        elif list_price:
            savings = f" ~~was ${list_price:.2f}~~"
        elif savings_pct:
            savings = f" \\({savings_pct}% off\\)"
        
        # Truncate long titles
        if len(title) > 80:
            title = title[:77] + "..."
        
        line = f"{i}\\. *{title}*"
        if author:
            line += f" — _{author}_"
        line += f" — {price_str}"
        if savings:
            line += f" {savings}"
        if url:
            line += f" — [Link]({url})"
        lines.append(line)
    
    lines.append("")
    lines.append("_🤖 Generated by Kindle Deals Bot_")
    
    return "\n".join(lines)


def format_empty_report() -> str:
    """Report when no sources returned data at all."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"📚 *Kindle SFF Deals — {now}*\n\n"
        "⚠️ Could not fetch deals from any source today\\. "
        "Amazon may be blocking requests or the selectors need updating\\.\n\n"
        "_🤖 Generated by Kindle Deals Bot_"
    )
